# Generated by Django 4.1.2 on 2022-10-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CocoPalaceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
